### ISSUE TITLE
Copy Changes

### ISSUE THREAD

**Issue by wetchler** [bayesimpact/bridge-uof#14]
1. On State Submission Tab, change “When ALL of your state's incidents for 2015 are fully ready …” to “When ALL of your jurisdiction’s incidents for 2015 are fully ready …”
2. On General Info, change “Number of officers involved” to “Number of officers involved from [agency name].”
3. On civilian page, on "civilian arrested and/or in custody" question, change "In custody" to two options -- "In custody (W&I section 5150)" (which does NOT ask for a charge code) and "In custody (other)" (which DOES ask for a charge code).
4. On civilian page, change "resistance" to "active resistance" on both question and hover
5. On civ&officer pages in injury section, change "injury caused by pre-existing condition" to "medical aid received due to pre-existing condition", and hide this question if no medical aid received
6. On officer page, change "to effect arrest" to "to effect arrest or take into custody"

**Comment by money** [comment]
https://github.com/bayesimpact/bridge-uof/pull/32
