### ISSUE TITLE
Bulk uploaded incidents don't create reverse relations (same for fake-generated incidents)

### ISSUE THREAD

**Issue by wetchler** [bayesimpact/bridge-uof#42]
When incidents are bulk uploaded, the sub-models (screener, general_info, involved_civilian, involved_officer) do not have a field linking back to the incident (`incident_ids`) that should be there (and is there in manually created incidents). It seems that *mostly* this doesn't matter, but in one case it does. Since general_info's "incident_id" is delegated to its linked incident, on the review page, incident id does not show up for these incidents. To reproduce:

1. Bulk upload test.json
2. Go to "View" one of the incidents
3. You'll see the incident ID is missing.
4. If you edit the general info, you'll see that it comes back, as saving it creates the link correctly.

**Comment by AlexNisnevich** [comment]
Ugh, that's awful.

Well, I can do some digging and try to figure this out. Or do you want to work on it since you're already knee-deep in this code, @everett-wetchler ?
